name: language_picker
description: Language picker dropdown and dialog.
version: 0.4.0
homepage: http://blog.wafrat.com/
repository: https://github.com/atn832/language_picker

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  recase: ^4.0.0
